# Installation: https://github.com/causefx/Organizr/

services:
  organizr:
    image: organizr/organizr:latest
    container_name: organizr
    pull_policy: always # set to 'always' when using 'latest' image
    environment:
      - PUID=${ORGANIZR_PUID}
      - PGID=${ORGANIZR_PGID}
    volumes:
      - /opt/appdata/organizrv2:/config
    ports:
      - 9284:80
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
