# Installation: https://hub.docker.com/_/adminer

services:
  adminer:
    image: adminer:4.17.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8686:8080
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
