# Installation: https://hub.docker.com/_/solr

services:
  solr:
    image: solr:9.8.0
    container_name: solr
    ports:
      - 8626:8983
    volumes:
      - /opt/appdata/solr:/var/solr
    command:
      - solr-precreate
      - gettingstarted
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
