# Installation: https://hub.docker.com/r/cturra/ntp

services:
  ntp:
    image: cturra/ntp:latest
    container_name: ntp
    pull_policy: always # set to 'always' when using 'latest' image
    environment:
      - NTP_SERVERS=${NTP_SERVERS}
      - ENABLE_NTS='true'
      - TZ=${NTP_TZ}
    restart: unless-stopped
    ports:
      - 1016:123/udp
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
