# Installation: https://hub.docker.com/r/tonistiigi/binfmt

services:
  binfmt:
    image: tonistiigi/binfmt:latest
    container_name: binfmt
    pull_policy: always # set to 'always' when using 'latest' image
    command: --install all
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
