# Installation: https://hub.docker.com/r/inrix/floatplane-downloader

services:
  floatplane-downloader:
    image: inrix/floatplane-downloader:latest
    container_name: floatplane-downloader
    pull_policy: always # set to 'always' when using 'latest' image
    volumes:
      - /opt/appdata/floatplanedownloader/db:/fp/db
      - /opt/appdata/media:/fp/videos
    tty: true # To be able to reply to interactive prompts.
    stdin_open: true # For interactive flag.
    restart: unless-stopped
    environment:
      - headless=${FLOATPLANE_DOWNLOADER_HEADLESS}
      - username=${FLOATPLANE_DOWNLOADER_USERNAME}
      - password=${FLOATPLANE_DOWNLOADER_PASSWORD}
      - plexUsername=${FLOATPLANE_DOWNLOADER_PLEXUSERNAME}
      - plexPassword=${FLOATPLANE_DOWNLOADER_PLEXPASSWORD}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
