# Installation: https://docs.gitlab.com/ee/install/docker.html

services:
  gitlab:
    image: gitlab/gitlab-ce:17.9.0-ce.0
    container_name: gitlab-ce
    privileged: true
    environment:
      - GITLAB_OMNIBUS_CONFIG=${GITLAB_OMNIBUS_CONFIG}
    ports:
      - 1011:22
      - 1012:80
      - 1013:443
    volumes:
      - /opt/appdata/gitlab/config:/etc/gitlab
      - /opt/appdata/gitlab/logs:/var/log/gitlab
      - /opt/appdata/gitlab/data:/var/opt/gitlab
    shm_size: 256m
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
