# Installation: https://hub.docker.com/r/containrrr/watchtower

services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_METRICS=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300 # Poll every 5 minutes
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN} # Secure HTTP API
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    command: --debug --http-api-update --http-api-metrics --cleanup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8080:8080' # HTTP API endpoint for updates
      - '9090:9090' # Metrics endpoint
    restart: always
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
