# Installation: https://github.com/tubearchivist/tubearchivist

services:
  tubearchivist:
    image: bbilly1/tubearchivist:v0.5.0
    container_name: tubearchivist
    restart: unless-stopped
    ports:
      - 8953:8000
    volumes:
      - /opt/appdata/tubearchivist/media:/youtube
      - /opt/appdata/tubearchivist/cache:/cache
    environment:
      - ES_URL=${TUBEARCHIVIST_ES_URL}
      - REDIS_HOST=${TUBEARCHIVIST_REDIS_HOST}
      - HOST_UID=${TUBEARCHIVIST_HOST_UID}
      - HOST_GID=${TUBEARCHIVIST_HOST_GID}
      - TA_HOST=${TUBEARCHIVIST_TA_HOST}
      - TA_USERNAME=${TUBEARCHIVIST_TA_USERNAME}
      - TA_PASSWORD=${TUBEARCHIVIST_TA_PASSWORD}
      - ELASTIC_PASSWORD=${TUBEARCHIVIST_ELASTIC_PASSWORD}
      - TZ=${TUBEARCHIVIST_TZ}
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - proxy

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    hostname: archivist-redis
    restart: unless-stopped
    ports:
      - 8952:6379
    volumes:
      - /opt/appdata/tubearchivist-redis:/data
    depends_on:
      - archivist-es
    networks:
      - proxy

  archivist-es:
    image: bbilly1/tubearchivist-es # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - ELASTIC_PASSWORD=${ARCHIVIST_ES_ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=${ARCHIVIST_ES_ES_JAVA_OPTS}
      - xpack.security.enabled=${ARCHIVIST_ES_xpack.security.enabled}
      - discovery.type=${ARCHIVIST_ES_discovery.type}
      - path.repo=${ARCHIVIST_ES_path.repo}
    volumes:
      - /opt/appdata/tubearchivist-es:/usr/share/elasticsearch/data
    expose:
      - '9200'
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
