services:
  bitwardensync:
    image: norkz/bitwardensync:1.0.2
    container_name: bitwardensync
    hostname: bitwardensync
    user: root
    environment:
      - BITWARDEN_SYNC_HOST=${BITWARDEN_SYNC_HOST:?error}
      - BITWARDEN_SYNC_BW_EMAIL_ADDRESS=${BITWARDEN_SYNC_BW_EMAIL_ADDRESS:?error}
      - BITWARDEN_SYNC_BW_PASSWORD=${BITWARDEN_SYNC_BW_PASSWORD:?error}
      - BITWARDEN_SYNC_BW_CLIENTID=${BITWARDEN_SYNC_BW_CLIENTID:?error}
      - BITWARDEN_SYNC_BW_CLIENTSECRET=${BITWARDEN_SYNC_BW_CLIENTSECRET:?error}
      - BITWARDEN_SYNC_IMPORT_FORMAT=${BITWARDEN_SYNC_IMPORT_FORMAT:?error}
      - BITWARDEN_SYNC_BW_OTP_CODE=${BITWARDEN_SYNC_BW_OTP_CODE:?error} # Optional
    volumes:
      - /opt/appdata/backuponepass/data:/bitwardensync/data # Password Manager Data Input
      - /opt/appdata/bitwardensync/data/docker/config:/root/.config/Bitwarden CLI # Where data.json file is created.
    restart: on-failure
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
