# Installation: https://hub.docker.com/r/louislam/uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    volumes:
      - /opt/appdata/uptime-kuma:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
