#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Generates Repo Tree once
bun run repoTree

# Format all Python files with Prettier once
bun run prettier:format

# Stage all changes, including new, modified, and deleted files
git add .
