# Installation: https://hub.docker.com/r/linuxserver/mariadb

services:
  mariadb:
    image: linuxserver/mariadb:11.4.4
    container_name: mariadb
    environment:
      - PUID=${MARIADB_PUID}
      - PGID=${MARIADB_PGID}
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - TZ=${MARIADB_TZ}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - /opt/appdata/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
    external: true
