# Installation: https://github.com/pterodactyl/panel
# Info:
# chmod -R 600 /opt/appdata/pterodactyl-panel/game.data/config.yml -- IF Panel changes configuration and breaks the node.

services:
  pterodactyl-panel:
    image: ccarney16/pterodactyl-panel:v1.11.10
    container_name: pterodactyl-panel
    ports:
      - 8025:80
    volumes:
      - /opt/appdata/pterodactyl-panel/:/app/var/ # Appdata
      - /opt/appdata/pterodactyl-wings:/etc/pterodactyl # Where config.yml goes into. # Appdata
      - /opt/appdata/pterodactyl-wings/data:/opt/appdata/pterodactyl-wings/data # Shared data between Panel and Wings.
    environment:
      - APP_ENV=${PTERODACTYL_PANEL_APP_ENV}
      - APP_ENVIRONMENT_ONLY=${PTERODACTYL_PANEL_APP_ENVIRONMENT_ONLY}
      - APP_SERVICE_AUTHOR=${PTERODACTYL_PANEL_APP_SERVICE_AUTHOR}
      - APP_URL=${PTERODACTYL_PANEL_APP_URL}
      - APP_TIMEZONE=${PTERODACTYL_PANEL_APP_TIMEZONE}
      - CACHE_DRIVER=${PTERODACTYL_PANEL_CACHE_DRIVER}
      - SESSION_DRIVER=${PTERODACTYL_PANEL_SESSION_DRIVER}
      - QUEUE_DRIVER=${PTERODACTYL_PANEL_QUEUE_DRIVER}
      - REDIS_HOST=${PTERODACTYL_PANEL_REDIS_HOST}
      - REDIS_PORT=${PTERODACTYL_PANEL_REDIS_PORT}
      - REDIS_USER=${PTERODACTYL_PANEL_REDIS_USER}
      - REDIS_PASSWORD=${PTERODACTYL_PANEL_REDIS_PASSWORD}
      - MAIL_FROM=${PTERODACTYL_PANEL_MAIL_FROM}
      - MAIL_DRIVER=${PTERODACTYL_PANEL_MAIL_DRIVER}
      - MAIL_HOST=${PTERODACTYL_PANEL_MAIL_HOST}
      - MAIL_PORT=${PTERODACTYL_PANEL_MAIL_PORT}
      - MAIL_USERNAME=${PTERODACTYL_PANEL_MAIL_USERNAME}
      - MAIL_PASSWORD=${PTERODACTYL_PANEL_MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${PTERODACTYL_PANEL_MAIL_ENCRYPTION}
      - APP_DEBUG=${PTERODACTYL_PANEL_APP_DEBUG}
      - TRUSTED_PROXIES=${PTERODACTYL_PANEL_TRUSTED_PROXIES}
      - DB_HOST=${PTERODACTYL_PANEL_DB_HOST}
      - DB_PORT=${PTERODACTYL_PANEL_DB_PORT}
      - DB_USER=${PTERODACTYL_PANEL_DB_USER}
      - DB_PASSWORD=${PTERODACTYL_PANEL_DB_PASSWORD}
      - DB_DATABASE=${PTERODACTYL_PANEL_DB_DATABASE}
    restart: unless-stopped
    depends_on:
      - pterodactyl-redis
      - pterodactyl-mariadb
    networks:
      - proxy

  pterodactyl-redis:
    image: redis:7.4.2
    container_name: pterodactyl-redis
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD-SHELL, redis-cli ping | grep PONG]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    restart: unless-stopped
    networks:
      - proxy

  pterodactyl-mariadb:
    image: linuxserver/mariadb:11.4.4
    container_name: pterodactyl-mariadb
    environment:
      - PUID=${PTERODACTYL_MARIADB_PUID}
      - PGID=${PTERODACTYL_MARIADB_PGID}
      - MYSQL_ROOT_PASSWORD=${PTERODACTYL_MARIADB_PASSWORD}
      - TZ=${PTERODACTYL_MARIADB_TZ}
      - MYSQL_DATABASE=${PTERODACTYL_MARIADB_DATABASE}
      - MYSQL_USER=${PTERODACTYL_MARIADB_USER}
      - MYSQL_PASSWORD=${PTERODACTYL_MARIADB_PASSWORD}
    volumes:
      - /opt/appdata/pterodactyl-panel/mariadb:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
